# Configurações gerais (fallback)
[build]
  command = "pnpm run build"
  publish = ".next"

# Configurações específicas para quando o Netlify buildar a branch v-1
[context.v-1]
  command = "pnpm run build"
  publish = ".next"